/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FastTrackRouteImport } from './routes/fast-track'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuleModuleIdRouteImport } from './routes/module.$moduleId'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FastTrackRoute = FastTrackRouteImport.update({
  id: '/fast-track',
  path: '/fast-track',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleModuleIdRoute = ModuleModuleIdRouteImport.update({
  id: '/module/$moduleId',
  path: '/module/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fast-track': typeof FastTrackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/vault': typeof VaultRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fast-track': typeof FastTrackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/vault': typeof VaultRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fast-track': typeof FastTrackRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/vault': typeof VaultRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fast-track'
    | '/login'
    | '/profile'
    | '/vault'
    | '/module/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fast-track'
    | '/login'
    | '/profile'
    | '/vault'
    | '/module/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/fast-track'
    | '/login'
    | '/profile'
    | '/vault'
    | '/module/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FastTrackRoute: typeof FastTrackRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  VaultRoute: typeof VaultRoute
  ModuleModuleIdRoute: typeof ModuleModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast-track': {
      id: '/fast-track'
      path: '/fast-track'
      fullPath: '/fast-track'
      preLoaderRoute: typeof FastTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$moduleId': {
      id: '/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/module/$moduleId'
      preLoaderRoute: typeof ModuleModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FastTrackRoute: FastTrackRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  VaultRoute: VaultRoute,
  ModuleModuleIdRoute: ModuleModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
