/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithMeRouteImport } from './routes/work-with-me'
import { Route as VaultThankYouRouteImport } from './routes/vault-thank-you'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UnsubscribedRouteImport } from './routes/unsubscribed'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as StarterVaultRouteImport } from './routes/starter-vault'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadKitRouteImport } from './routes/lead-kit'
import { Route as KrakenRouteImport } from './routes/kraken'
import { Route as JumpstartRouteImport } from './routes/jumpstart'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as GetMoreCustomers2RouteImport } from './routes/getmorecustomers2'
import { Route as GetMoreCustomersRouteImport } from './routes/getmorecustomers'
import { Route as FunnelRouteImport } from './routes/funnel'
import { Route as FastTrackRouteImport } from './routes/fast-track'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as BookRouteImport } from './routes/book'
import { Route as BizThankYouRouteImport } from './routes/biz-thank-you'
import { Route as BeginRouteImport } from './routes/begin'
import { Route as AiLeadKitRouteImport } from './routes/ai-lead-kit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StarterVaultIndexRouteImport } from './routes/starter-vault.index'
import { Route as IntelIndexRouteImport } from './routes/intel.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StarterVaultSlugRouteImport } from './routes/starter-vault.$slug'
import { Route as ModuleModuleIdRouteImport } from './routes/module.$moduleId'
import { Route as IntelSlugRouteImport } from './routes/intel.$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthProvisionRouteImport } from './routes/auth/provision'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiTestAiLeadKitRouteImport } from './routes/api/test-ai-lead-kit'
import { Route as ApiSubscribeVaultRouteImport } from './routes/api/subscribe-vault'
import { Route as ApiSubscribeBizRouteImport } from './routes/api/subscribe-biz'
import { Route as ApiSubscribeAiLeadKitRouteImport } from './routes/api/subscribe-ai-lead-kit'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiPublishResendTemplatesRouteImport } from './routes/api/publish-resend-templates'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminModulesRouteImport } from './routes/admin/modules'
import { Route as AdminIntelRouteImport } from './routes/admin/intel'
import { Route as AdminAvailabilityRouteImport } from './routes/admin/availability'
import { Route as AdminAssetsRouteImport } from './routes/admin/assets'
import { Route as ApiCdnKeyRouteImport } from './routes/api/cdn.$key'
import { Route as ApiBookingActionRouteImport } from './routes/api/booking.$action'
import { Route as AdminModulesModuleIdRouteImport } from './routes/admin/modules.$moduleId'
import { Route as ApiBookingAdminSettingsRouteImport } from './routes/api/booking.admin.settings'

const WorkWithMeRoute = WorkWithMeRouteImport.update({
  id: '/work-with-me',
  path: '/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultThankYouRoute = VaultThankYouRouteImport.update({
  id: '/vault-thank-you',
  path: '/vault-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribedRoute = UnsubscribedRouteImport.update({
  id: '/unsubscribed',
  path: '/unsubscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterVaultRoute = StarterVaultRouteImport.update({
  id: '/starter-vault',
  path: '/starter-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadKitRoute = LeadKitRouteImport.update({
  id: '/lead-kit',
  path: '/lead-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const KrakenRoute = KrakenRouteImport.update({
  id: '/kraken',
  path: '/kraken',
  getParentRoute: () => rootRouteImport,
} as any)
const JumpstartRoute = JumpstartRouteImport.update({
  id: '/jumpstart',
  path: '/jumpstart',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const GetMoreCustomers2Route = GetMoreCustomers2RouteImport.update({
  id: '/getmorecustomers2',
  path: '/getmorecustomers2',
  getParentRoute: () => rootRouteImport,
} as any)
const GetMoreCustomersRoute = GetMoreCustomersRouteImport.update({
  id: '/getmorecustomers',
  path: '/getmorecustomers',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelRoute = FunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const FastTrackRoute = FastTrackRouteImport.update({
  id: '/fast-track',
  path: '/fast-track',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BizThankYouRoute = BizThankYouRouteImport.update({
  id: '/biz-thank-you',
  path: '/biz-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginRoute = BeginRouteImport.update({
  id: '/begin',
  path: '/begin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLeadKitRoute = AiLeadKitRouteImport.update({
  id: '/ai-lead-kit',
  path: '/ai-lead-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterVaultIndexRoute = StarterVaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StarterVaultRoute,
} as any)
const IntelIndexRoute = IntelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntelRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StarterVaultSlugRoute = StarterVaultSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StarterVaultRoute,
} as any)
const ModuleModuleIdRoute = ModuleModuleIdRouteImport.update({
  id: '/module/$moduleId',
  path: '/module/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelSlugRoute = IntelSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IntelRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProvisionRoute = AuthProvisionRouteImport.update({
  id: '/auth/provision',
  path: '/auth/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestAiLeadKitRoute = ApiTestAiLeadKitRouteImport.update({
  id: '/api/test-ai-lead-kit',
  path: '/api/test-ai-lead-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeVaultRoute = ApiSubscribeVaultRouteImport.update({
  id: '/api/subscribe-vault',
  path: '/api/subscribe-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeBizRoute = ApiSubscribeBizRouteImport.update({
  id: '/api/subscribe-biz',
  path: '/api/subscribe-biz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeAiLeadKitRoute = ApiSubscribeAiLeadKitRouteImport.update({
  id: '/api/subscribe-ai-lead-kit',
  path: '/api/subscribe-ai-lead-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishResendTemplatesRoute =
  ApiPublishResendTemplatesRouteImport.update({
    id: '/api/publish-resend-templates',
    path: '/api/publish-resend-templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntelRoute = AdminIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCdnKeyRoute = ApiCdnKeyRouteImport.update({
  id: '/api/cdn/$key',
  path: '/api/cdn/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingActionRoute = ApiBookingActionRouteImport.update({
  id: '/api/booking/$action',
  path: '/api/booking/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulesModuleIdRoute = AdminModulesModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => AdminModulesRoute,
} as any)
const ApiBookingAdminSettingsRoute = ApiBookingAdminSettingsRouteImport.update({
  id: '/api/booking/admin/settings',
  path: '/api/booking/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-lead-kit': typeof AiLeadKitRoute
  '/begin': typeof BeginRoute
  '/biz-thank-you': typeof BizThankYouRoute
  '/book': typeof BookRoute
  '/cancel': typeof CancelRoute
  '/fast-track': typeof FastTrackRoute
  '/funnel': typeof FunnelRoute
  '/getmorecustomers': typeof GetMoreCustomersRoute
  '/getmorecustomers2': typeof GetMoreCustomers2Route
  '/intel': typeof IntelRouteWithChildren
  '/jumpstart': typeof JumpstartRoute
  '/kraken': typeof KrakenRoute
  '/lead-kit': typeof LeadKitRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/starter-vault': typeof StarterVaultRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/thank-you': typeof ThankYouRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/unsubscribed': typeof UnsubscribedRoute
  '/vault': typeof VaultRoute
  '/vault-thank-you': typeof VaultThankYouRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/intel': typeof AdminIntelRoute
  '/admin/modules': typeof AdminModulesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/contact': typeof ApiContactRoute
  '/api/publish-resend-templates': typeof ApiPublishResendTemplatesRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/subscribe-ai-lead-kit': typeof ApiSubscribeAiLeadKitRoute
  '/api/subscribe-biz': typeof ApiSubscribeBizRoute
  '/api/subscribe-vault': typeof ApiSubscribeVaultRoute
  '/api/test-ai-lead-kit': typeof ApiTestAiLeadKitRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/provision': typeof AuthProvisionRoute
  '/auth/register': typeof AuthRegisterRoute
  '/intel/$slug': typeof IntelSlugRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/starter-vault/$slug': typeof StarterVaultSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/intel/': typeof IntelIndexRoute
  '/starter-vault/': typeof StarterVaultIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/api/booking/$action': typeof ApiBookingActionRoute
  '/api/cdn/$key': typeof ApiCdnKeyRoute
  '/api/booking/admin/settings': typeof ApiBookingAdminSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-lead-kit': typeof AiLeadKitRoute
  '/begin': typeof BeginRoute
  '/biz-thank-you': typeof BizThankYouRoute
  '/book': typeof BookRoute
  '/cancel': typeof CancelRoute
  '/fast-track': typeof FastTrackRoute
  '/funnel': typeof FunnelRoute
  '/getmorecustomers': typeof GetMoreCustomersRoute
  '/getmorecustomers2': typeof GetMoreCustomers2Route
  '/jumpstart': typeof JumpstartRoute
  '/kraken': typeof KrakenRoute
  '/lead-kit': typeof LeadKitRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/subscribe': typeof SubscribeRoute
  '/thank-you': typeof ThankYouRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/unsubscribed': typeof UnsubscribedRoute
  '/vault': typeof VaultRoute
  '/vault-thank-you': typeof VaultThankYouRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/intel': typeof AdminIntelRoute
  '/admin/modules': typeof AdminModulesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/contact': typeof ApiContactRoute
  '/api/publish-resend-templates': typeof ApiPublishResendTemplatesRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/subscribe-ai-lead-kit': typeof ApiSubscribeAiLeadKitRoute
  '/api/subscribe-biz': typeof ApiSubscribeBizRoute
  '/api/subscribe-vault': typeof ApiSubscribeVaultRoute
  '/api/test-ai-lead-kit': typeof ApiTestAiLeadKitRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/provision': typeof AuthProvisionRoute
  '/auth/register': typeof AuthRegisterRoute
  '/intel/$slug': typeof IntelSlugRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/starter-vault/$slug': typeof StarterVaultSlugRoute
  '/admin': typeof AdminIndexRoute
  '/intel': typeof IntelIndexRoute
  '/starter-vault': typeof StarterVaultIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/api/booking/$action': typeof ApiBookingActionRoute
  '/api/cdn/$key': typeof ApiCdnKeyRoute
  '/api/booking/admin/settings': typeof ApiBookingAdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-lead-kit': typeof AiLeadKitRoute
  '/begin': typeof BeginRoute
  '/biz-thank-you': typeof BizThankYouRoute
  '/book': typeof BookRoute
  '/cancel': typeof CancelRoute
  '/fast-track': typeof FastTrackRoute
  '/funnel': typeof FunnelRoute
  '/getmorecustomers': typeof GetMoreCustomersRoute
  '/getmorecustomers2': typeof GetMoreCustomers2Route
  '/intel': typeof IntelRouteWithChildren
  '/jumpstart': typeof JumpstartRoute
  '/kraken': typeof KrakenRoute
  '/lead-kit': typeof LeadKitRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/starter-vault': typeof StarterVaultRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/thank-you': typeof ThankYouRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/unsubscribed': typeof UnsubscribedRoute
  '/vault': typeof VaultRoute
  '/vault-thank-you': typeof VaultThankYouRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/intel': typeof AdminIntelRoute
  '/admin/modules': typeof AdminModulesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/contact': typeof ApiContactRoute
  '/api/publish-resend-templates': typeof ApiPublishResendTemplatesRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/subscribe-ai-lead-kit': typeof ApiSubscribeAiLeadKitRoute
  '/api/subscribe-biz': typeof ApiSubscribeBizRoute
  '/api/subscribe-vault': typeof ApiSubscribeVaultRoute
  '/api/test-ai-lead-kit': typeof ApiTestAiLeadKitRoute
  '/api/upload': typeof ApiUploadRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/provision': typeof AuthProvisionRoute
  '/auth/register': typeof AuthRegisterRoute
  '/intel/$slug': typeof IntelSlugRoute
  '/module/$moduleId': typeof ModuleModuleIdRoute
  '/starter-vault/$slug': typeof StarterVaultSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/intel/': typeof IntelIndexRoute
  '/starter-vault/': typeof StarterVaultIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/api/booking/$action': typeof ApiBookingActionRoute
  '/api/cdn/$key': typeof ApiCdnKeyRoute
  '/api/booking/admin/settings': typeof ApiBookingAdminSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-lead-kit'
    | '/begin'
    | '/biz-thank-you'
    | '/book'
    | '/cancel'
    | '/fast-track'
    | '/funnel'
    | '/getmorecustomers'
    | '/intel'
    | '/jumpstart'
    | '/kraken'
    | '/lead-kit'
    | '/login'
    | '/offer'
    | '/profile'
    | '/register'
    | '/starter-vault'
    | '/subscribe'
    | '/thank-you'
    | '/unsubscribe'
    | '/unsubscribed'
    | '/vault'
    | '/vault-thank-you'
    | '/work-with-me'
    | '/admin/assets'
    | '/admin/availability'
    | '/admin/intel'
    | '/admin/modules'
    | '/admin/users'
    | '/api/checkout'
    | '/api/contact'
    | '/api/publish-resend-templates'
    | '/api/stripe-webhook'
    | '/api/subscribe-ai-lead-kit'
    | '/api/subscribe-biz'
    | '/api/subscribe-vault'
    | '/api/test-ai-lead-kit'
    | '/api/upload'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/provision'
    | '/auth/register'
    | '/intel/$slug'
    | '/module/$moduleId'
    | '/starter-vault/$slug'
    | '/admin/'
    | '/intel/'
    | '/starter-vault/'
    | '/admin/modules/$moduleId'
    | '/api/booking/$action'
    | '/api/cdn/$key'
    | '/api/booking/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-lead-kit'
    | '/begin'
    | '/biz-thank-you'
    | '/book'
    | '/cancel'
    | '/fast-track'
    | '/funnel'
    | '/getmorecustomers'
    | '/jumpstart'
    | '/kraken'
    | '/lead-kit'
    | '/login'
    | '/offer'
    | '/profile'
    | '/register'
    | '/subscribe'
    | '/thank-you'
    | '/unsubscribe'
    | '/unsubscribed'
    | '/vault'
    | '/vault-thank-you'
    | '/work-with-me'
    | '/admin/assets'
    | '/admin/availability'
    | '/admin/intel'
    | '/admin/modules'
    | '/admin/users'
    | '/api/checkout'
    | '/api/contact'
    | '/api/publish-resend-templates'
    | '/api/stripe-webhook'
    | '/api/subscribe-ai-lead-kit'
    | '/api/subscribe-biz'
    | '/api/subscribe-vault'
    | '/api/test-ai-lead-kit'
    | '/api/upload'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/provision'
    | '/auth/register'
    | '/intel/$slug'
    | '/module/$moduleId'
    | '/starter-vault/$slug'
    | '/admin'
    | '/intel'
    | '/starter-vault'
    | '/admin/modules/$moduleId'
    | '/api/booking/$action'
    | '/api/cdn/$key'
    | '/api/booking/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-lead-kit'
    | '/begin'
    | '/biz-thank-you'
    | '/book'
    | '/cancel'
    | '/fast-track'
    | '/funnel'
    | '/getmorecustomers'
    | '/intel'
    | '/jumpstart'
    | '/kraken'
    | '/lead-kit'
    | '/login'
    | '/offer'
    | '/profile'
    | '/register'
    | '/starter-vault'
    | '/subscribe'
    | '/thank-you'
    | '/unsubscribe'
    | '/unsubscribed'
    | '/vault'
    | '/vault-thank-you'
    | '/work-with-me'
    | '/admin/assets'
    | '/admin/availability'
    | '/admin/intel'
    | '/admin/modules'
    | '/admin/users'
    | '/api/checkout'
    | '/api/contact'
    | '/api/publish-resend-templates'
    | '/api/stripe-webhook'
    | '/api/subscribe-ai-lead-kit'
    | '/api/subscribe-biz'
    | '/api/subscribe-vault'
    | '/api/test-ai-lead-kit'
    | '/api/upload'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/provision'
    | '/auth/register'
    | '/intel/$slug'
    | '/module/$moduleId'
    | '/starter-vault/$slug'
    | '/admin/'
    | '/intel/'
    | '/starter-vault/'
    | '/admin/modules/$moduleId'
    | '/api/booking/$action'
    | '/api/cdn/$key'
    | '/api/booking/admin/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiLeadKitRoute: typeof AiLeadKitRoute
  BeginRoute: typeof BeginRoute
  BizThankYouRoute: typeof BizThankYouRoute
  BookRoute: typeof BookRoute
  CancelRoute: typeof CancelRoute
  FastTrackRoute: typeof FastTrackRoute
  FunnelRoute: typeof FunnelRoute
  GetMoreCustomersRoute: typeof GetMoreCustomersRoute
  GetMoreCustomers2Route: typeof GetMoreCustomers2Route
  IntelRoute: typeof IntelRouteWithChildren
  JumpstartRoute: typeof JumpstartRoute
  KrakenRoute: typeof KrakenRoute
  LeadKitRoute: typeof LeadKitRoute
  LoginRoute: typeof LoginRoute
  OfferRoute: typeof OfferRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  StarterVaultRoute: typeof StarterVaultRouteWithChildren
  SubscribeRoute: typeof SubscribeRoute
  ThankYouRoute: typeof ThankYouRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  UnsubscribedRoute: typeof UnsubscribedRoute
  VaultRoute: typeof VaultRoute
  VaultThankYouRoute: typeof VaultThankYouRoute
  WorkWithMeRoute: typeof WorkWithMeRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiPublishResendTemplatesRoute: typeof ApiPublishResendTemplatesRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiSubscribeAiLeadKitRoute: typeof ApiSubscribeAiLeadKitRoute
  ApiSubscribeBizRoute: typeof ApiSubscribeBizRoute
  ApiSubscribeVaultRoute: typeof ApiSubscribeVaultRoute
  ApiTestAiLeadKitRoute: typeof ApiTestAiLeadKitRoute
  ApiUploadRoute: typeof ApiUploadRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthProvisionRoute: typeof AuthProvisionRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ModuleModuleIdRoute: typeof ModuleModuleIdRoute
  ApiBookingActionRoute: typeof ApiBookingActionRoute
  ApiCdnKeyRoute: typeof ApiCdnKeyRoute
  ApiBookingAdminSettingsRoute: typeof ApiBookingAdminSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-me': {
      id: '/work-with-me'
      path: '/work-with-me'
      fullPath: '/work-with-me'
      preLoaderRoute: typeof WorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault-thank-you': {
      id: '/vault-thank-you'
      path: '/vault-thank-you'
      fullPath: '/vault-thank-you'
      preLoaderRoute: typeof VaultThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribed': {
      id: '/unsubscribed'
      path: '/unsubscribed'
      fullPath: '/unsubscribed'
      preLoaderRoute: typeof UnsubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter-vault': {
      id: '/starter-vault'
      path: '/starter-vault'
      fullPath: '/starter-vault'
      preLoaderRoute: typeof StarterVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-kit': {
      id: '/lead-kit'
      path: '/lead-kit'
      fullPath: '/lead-kit'
      preLoaderRoute: typeof LeadKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kraken': {
      id: '/kraken'
      path: '/kraken'
      fullPath: '/kraken'
      preLoaderRoute: typeof KrakenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jumpstart': {
      id: '/jumpstart'
      path: '/jumpstart'
      fullPath: '/jumpstart'
      preLoaderRoute: typeof JumpstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnel': {
      id: '/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof FunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getmorecustomers': {
      id: '/getmorecustomers'
      path: '/getmorecustomers'
      fullPath: '/getmorecustomers'
      preLoaderRoute: typeof GetMoreCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getmorecustomers2': {
      id: '/getmorecustomers2'
      path: '/getmorecustomers2'
      fullPath: '/getmorecustomers2'
      preLoaderRoute: typeof GetMoreCustomers2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast-track': {
      id: '/fast-track'
      path: '/fast-track'
      fullPath: '/fast-track'
      preLoaderRoute: typeof FastTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz-thank-you': {
      id: '/biz-thank-you'
      path: '/biz-thank-you'
      fullPath: '/biz-thank-you'
      preLoaderRoute: typeof BizThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin': {
      id: '/begin'
      path: '/begin'
      fullPath: '/begin'
      preLoaderRoute: typeof BeginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lead-kit': {
      id: '/ai-lead-kit'
      path: '/ai-lead-kit'
      fullPath: '/ai-lead-kit'
      preLoaderRoute: typeof AiLeadKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter-vault/': {
      id: '/starter-vault/'
      path: '/'
      fullPath: '/starter-vault/'
      preLoaderRoute: typeof StarterVaultIndexRouteImport
      parentRoute: typeof StarterVaultRoute
    }
    '/intel/': {
      id: '/intel/'
      path: '/'
      fullPath: '/intel/'
      preLoaderRoute: typeof IntelIndexRouteImport
      parentRoute: typeof IntelRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/starter-vault/$slug': {
      id: '/starter-vault/$slug'
      path: '/$slug'
      fullPath: '/starter-vault/$slug'
      preLoaderRoute: typeof StarterVaultSlugRouteImport
      parentRoute: typeof StarterVaultRoute
    }
    '/module/$moduleId': {
      id: '/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/module/$moduleId'
      preLoaderRoute: typeof ModuleModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel/$slug': {
      id: '/intel/$slug'
      path: '/$slug'
      fullPath: '/intel/$slug'
      preLoaderRoute: typeof IntelSlugRouteImport
      parentRoute: typeof IntelRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/provision': {
      id: '/auth/provision'
      path: '/auth/provision'
      fullPath: '/auth/provision'
      preLoaderRoute: typeof AuthProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-ai-lead-kit': {
      id: '/api/test-ai-lead-kit'
      path: '/api/test-ai-lead-kit'
      fullPath: '/api/test-ai-lead-kit'
      preLoaderRoute: typeof ApiTestAiLeadKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe-vault': {
      id: '/api/subscribe-vault'
      path: '/api/subscribe-vault'
      fullPath: '/api/subscribe-vault'
      preLoaderRoute: typeof ApiSubscribeVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe-biz': {
      id: '/api/subscribe-biz'
      path: '/api/subscribe-biz'
      fullPath: '/api/subscribe-biz'
      preLoaderRoute: typeof ApiSubscribeBizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe-ai-lead-kit': {
      id: '/api/subscribe-ai-lead-kit'
      path: '/api/subscribe-ai-lead-kit'
      fullPath: '/api/subscribe-ai-lead-kit'
      preLoaderRoute: typeof ApiSubscribeAiLeadKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish-resend-templates': {
      id: '/api/publish-resend-templates'
      path: '/api/publish-resend-templates'
      fullPath: '/api/publish-resend-templates'
      preLoaderRoute: typeof ApiPublishResendTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intel': {
      id: '/admin/intel'
      path: '/intel'
      fullPath: '/admin/intel'
      preLoaderRoute: typeof AdminIntelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/cdn/$key': {
      id: '/api/cdn/$key'
      path: '/api/cdn/$key'
      fullPath: '/api/cdn/$key'
      preLoaderRoute: typeof ApiCdnKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking/$action': {
      id: '/api/booking/$action'
      path: '/api/booking/$action'
      fullPath: '/api/booking/$action'
      preLoaderRoute: typeof ApiBookingActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modules/$moduleId': {
      id: '/admin/modules/$moduleId'
      path: '/$moduleId'
      fullPath: '/admin/modules/$moduleId'
      preLoaderRoute: typeof AdminModulesModuleIdRouteImport
      parentRoute: typeof AdminModulesRoute
    }
    '/api/booking/admin/settings': {
      id: '/api/booking/admin/settings'
      path: '/api/booking/admin/settings'
      fullPath: '/api/booking/admin/settings'
      preLoaderRoute: typeof ApiBookingAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminModulesRouteChildren {
  AdminModulesModuleIdRoute: typeof AdminModulesModuleIdRoute
}

const AdminModulesRouteChildren: AdminModulesRouteChildren = {
  AdminModulesModuleIdRoute: AdminModulesModuleIdRoute,
}

const AdminModulesRouteWithChildren = AdminModulesRoute._addFileChildren(
  AdminModulesRouteChildren,
)

interface AdminRouteChildren {
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminIntelRoute: typeof AdminIntelRoute
  AdminModulesRoute: typeof AdminModulesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssetsRoute: AdminAssetsRoute,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminIntelRoute: AdminIntelRoute,
  AdminModulesRoute: AdminModulesRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface IntelRouteChildren {
  IntelSlugRoute: typeof IntelSlugRoute
  IntelIndexRoute: typeof IntelIndexRoute
}

const IntelRouteChildren: IntelRouteChildren = {
  IntelSlugRoute: IntelSlugRoute,
  IntelIndexRoute: IntelIndexRoute,
}

const IntelRouteWithChildren = IntelRoute._addFileChildren(IntelRouteChildren)

interface StarterVaultRouteChildren {
  StarterVaultSlugRoute: typeof StarterVaultSlugRoute
  StarterVaultIndexRoute: typeof StarterVaultIndexRoute
}

const StarterVaultRouteChildren: StarterVaultRouteChildren = {
  StarterVaultSlugRoute: StarterVaultSlugRoute,
  StarterVaultIndexRoute: StarterVaultIndexRoute,
}

const StarterVaultRouteWithChildren = StarterVaultRoute._addFileChildren(
  StarterVaultRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiLeadKitRoute: AiLeadKitRoute,
  BeginRoute: BeginRoute,
  BizThankYouRoute: BizThankYouRoute,
  BookRoute: BookRoute,
  CancelRoute: CancelRoute,
  FastTrackRoute: FastTrackRoute,
  FunnelRoute: FunnelRoute,
  GetMoreCustomersRoute: GetMoreCustomersRoute,
  GetMoreCustomers2Route: GetMoreCustomers2Route,
  IntelRoute: IntelRouteWithChildren,
  JumpstartRoute: JumpstartRoute,
  KrakenRoute: KrakenRoute,
  LeadKitRoute: LeadKitRoute,
  LoginRoute: LoginRoute,
  OfferRoute: OfferRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  StarterVaultRoute: StarterVaultRouteWithChildren,
  SubscribeRoute: SubscribeRoute,
  ThankYouRoute: ThankYouRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  UnsubscribedRoute: UnsubscribedRoute,
  VaultRoute: VaultRoute,
  VaultThankYouRoute: VaultThankYouRoute,
  WorkWithMeRoute: WorkWithMeRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiContactRoute: ApiContactRoute,
  ApiPublishResendTemplatesRoute: ApiPublishResendTemplatesRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiSubscribeAiLeadKitRoute: ApiSubscribeAiLeadKitRoute,
  ApiSubscribeBizRoute: ApiSubscribeBizRoute,
  ApiSubscribeVaultRoute: ApiSubscribeVaultRoute,
  ApiTestAiLeadKitRoute: ApiTestAiLeadKitRoute,
  ApiUploadRoute: ApiUploadRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthProvisionRoute: AuthProvisionRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ModuleModuleIdRoute: ModuleModuleIdRoute,
  ApiBookingActionRoute: ApiBookingActionRoute,
  ApiCdnKeyRoute: ApiCdnKeyRoute,
  ApiBookingAdminSettingsRoute: ApiBookingAdminSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
